# Site settings
author: Seyedpouya hajiseyedjavadi
title: 
header-img: img/home-bg.png
email: pouya.javadi.resume@gmail.com
copyright_name: Seyedpouya hajiseyedjavadi
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  pjavadi84

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
